# Generated by Django 3.2.9 on 2021-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togather_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='answer',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
