# Generated by Django 3.2.9 on 2021-11-26 06:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('phone', models.BooleanField(default=True)),
                ('department', models.BooleanField(default=True)),
                ('age', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_form', to='user.group')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('require', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('S', '단답형'), ('L', '장문형')], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apply_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_form_question', to='togather_apply.applyform')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=30)),
                ('age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('X', '응답거부')], max_length=1)),
                ('answer', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apply_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='togather_apply.applyform')),
            ],
        ),
    ]
