# Generated by Django 3.2.9 on 2021-11-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togather_question', '0003_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
