# Generated by Django 3.2.9 on 2021-11-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togather_promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
    ]
